/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as SessionsNewRouteImport } from './routes/sessions.new'
import { Route as AthletesIdRouteImport } from './routes/athletes.$id'
import { Route as SessionsHockeyIdRouteImport } from './routes/sessions.hockey.$id'
import { Route as SessionsFencingIdRouteImport } from './routes/sessions.fencing.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesIdRoute = AthletesIdRouteImport.update({
  id: '/athletes/$id',
  path: '/athletes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsHockeyIdRoute = SessionsHockeyIdRouteImport.update({
  id: '/sessions/hockey/$id',
  path: '/sessions/hockey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsFencingIdRoute = SessionsFencingIdRouteImport.update({
  id: '/sessions/fencing/$id',
  path: '/sessions/fencing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/videos/$id': typeof VideosIdRoute
  '/sessions/fencing/$id': typeof SessionsFencingIdRoute
  '/sessions/hockey/$id': typeof SessionsHockeyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/videos/$id': typeof VideosIdRoute
  '/sessions/fencing/$id': typeof SessionsFencingIdRoute
  '/sessions/hockey/$id': typeof SessionsHockeyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/athletes/$id': typeof AthletesIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/videos/$id': typeof VideosIdRoute
  '/sessions/fencing/$id': typeof SessionsFencingIdRoute
  '/sessions/hockey/$id': typeof SessionsHockeyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/athletes/$id'
    | '/sessions/new'
    | '/videos/$id'
    | '/sessions/fencing/$id'
    | '/sessions/hockey/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/athletes/$id'
    | '/sessions/new'
    | '/videos/$id'
    | '/sessions/fencing/$id'
    | '/sessions/hockey/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/athletes/$id'
    | '/sessions/new'
    | '/videos/$id'
    | '/sessions/fencing/$id'
    | '/sessions/hockey/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AthletesIdRoute: typeof AthletesIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  VideosIdRoute: typeof VideosIdRoute
  SessionsFencingIdRoute: typeof SessionsFencingIdRoute
  SessionsHockeyIdRoute: typeof SessionsHockeyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$id': {
      id: '/athletes/$id'
      path: '/athletes/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AthletesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/hockey/$id': {
      id: '/sessions/hockey/$id'
      path: '/sessions/hockey/$id'
      fullPath: '/sessions/hockey/$id'
      preLoaderRoute: typeof SessionsHockeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/fencing/$id': {
      id: '/sessions/fencing/$id'
      path: '/sessions/fencing/$id'
      fullPath: '/sessions/fencing/$id'
      preLoaderRoute: typeof SessionsFencingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AthletesIdRoute: AthletesIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  VideosIdRoute: VideosIdRoute,
  SessionsFencingIdRoute: SessionsFencingIdRoute,
  SessionsHockeyIdRoute: SessionsHockeyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
